//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentChallenge.Data.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevelopmentChallenge.Data.Idiomas.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista vacía de formas!.
        /// </summary>
        internal static string EMTPY_LIST {
            get {
                return ResourceManager.GetString("EMTPY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Círculo.
        /// </summary>
        internal static string SHAPE_CIRCLE {
            get {
                return ResourceManager.GetString("SHAPE_CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuadrado.
        /// </summary>
        internal static string SHAPE_SQUARE {
            get {
                return ResourceManager.GetString("SHAPE_SQUARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapecio.
        /// </summary>
        internal static string SHAPE_TRAPEZE {
            get {
                return ResourceManager.GetString("SHAPE_TRAPEZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triángulo.
        /// </summary>
        internal static string SHAPE_TRIANGLE {
            get {
                return ResourceManager.GetString("SHAPE_TRIANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a formas.
        /// </summary>
        internal static string SHAPES_CAPTION {
            get {
                return ResourceManager.GetString("SHAPES_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de Formas.
        /// </summary>
        internal static string SHAPES_REPORT {
            get {
                return ResourceManager.GetString("SHAPES_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area.
        /// </summary>
        internal static string TITLE_AREA {
            get {
                return ResourceManager.GetString("TITLE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perimetro.
        /// </summary>
        internal static string TITLE_PERIMETER {
            get {
                return ResourceManager.GetString("TITLE_PERIMETER", resourceCulture);
            }
        }
    }
}
